language: ruby
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:
    - name: "build chroot centos/7 - bionic"
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          - sudo make deploy-libvirt
          - sudo make deploy-vagrant                             
          - sudo make deploy-vagrantfile 
          - sudo vagrant box add "centos/7" --provider=libvirt
          - sudo vagrant init --template templates/Vagrantfile.chroot.erb
          - sudo vagrant up --provider=libvirt vg-chroot-01
      after_success:
        - deactivate      

